---

  - include: "install-consul.yml"

  - include: consul-server-config.yml
    when: consul_server is defined

  - include: consul-client-config.yml
    when: consul_servicename is defined and consul_server is not defined
    tags:
      - consul-client-config

